---
# Fish shell environment configuration

- name: Global Environment Variables
  hosts: all
  become: true
  vars:
    pager:
      - set -Ux PAGER ov
      - set -Ux MANPAGER ov

- name: Local Environment Variables
  hosts: all
  become: false
  vars:
