---
- name: Personal PC Setup
  hosts: personal_pc
  become: true
  vars:
    user_name: rkopli
    user_password: "{{ 'mypassword' | password_hash('sha512') }}"

    gui_system_utilities:
      - gotop

    gui_user_programs:
      - vscode
      - discord clone
      - floorp
      - wezterm

    tui_system_utilities:
      - docker-ce

    tui_user_programs:
      - spotify-tui

    vscode_extensions:
      - ms-python.python
      - ms-vscode.cpptools

  # tasks: TODO!
  # change default terminal with 'sudo update-alternatives --config x-terminal-emulator' after adding wezterm as alternative

  # run chsh -s /usr/bin/fish
